### ISSUE TITLE
Error messages without further information

### ISSUE THREAD

**Issue by runningman84** [fluxcd/helm-operator#36] opened 2019-08-21 20:21 UTC
**Describe the bug**
I get the error "Object 'Kind' is missing in 'null'. Without any reference I am unable to fix this. We need a better error message complaining about the corresponding manifest file or something like that.

**Logs**
```
flux/flux-78dc8cc7d8-sr526[flux]: ts=2019-08-21T20:16:15.395032417Z caller=warming.go:198 component=warmer info="refreshing image" image=quay.io/prometheus/prometheus tag_count=95 to_update=95 of_which_refresh=0 of_which_missing=95
flux/flux-helm-operator-dff8b66b4-fhf6x[flux-helm-operator]: ts=2019-08-21T20:16:17.803965983Z caller=release.go:568 component=release err="Object 'Kind' is missing in 'null'"
flux/flux-helm-operator-dff8b66b4-fhf6x[flux-helm-operator]: ts=2019-08-21T20:16:17.851680342Z caller=release.go:568 component=release err="Object 'Kind' is missing in 'null'"
flux/flux-helm-operator-dff8b66b4-fhf6x[flux-helm-operator]: ts=2019-08-21T20:16:17.866927428Z caller=release.go:568 component=release err="Object 'Kind' is missing in 'null'"
flux/flux-helm-operator-dff8b66b4-fhf6x[flux-helm-operator]: ts=2019-08-21T20:16:17.884564751Z caller=release.go:568 component=release err="Object 'Kind' is missing in 'null'"
flux/flux-helm-operator-dff8b66b4-fhf6x[flux-helm-operator]: ts=2019-08-21T20:16:17.898444433Z caller=release.go:568 component=release err="Object 'Kind' is missing in 'null'"
```

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 0.10.1
- Kubernetes version: 1.14
- Git provider: github
- Container registry provider: docker hub

**Comment by demisx** [comment] 2019-11-06 19:57
Receiving the same error with prometheus operator here too. Not sure what that is. A better error message would definitely help.

**Comment by hiddeco** [comment] 2019-11-08 11:28
This has been resolved in #47, which became available in `v1.0.0-rc2`.

**Closed as completed by hiddeco** 2019-11-08 11:28 UTC
Labels: bug, blocked needs validation

**Comment by demisx** [comment] 2019-11-08 18:39
@hiddeco Thank you very much for letting us know. I see that helm chart is [still referencing `v0.10.1`](https://github.com/fluxcd/flux/blob/master/chart/flux/values.yaml#L25). What is the current process for upgrading helm operator version? Do we wait until `v1.0.0` stable is released?

**Comment by kav** [comment] 2019-12-24 19:26
I'm seeing the issue in v1.0.0-rc5. @hiddeco is there a regression? Need more info? This is on a helm v3 deployment

**Comment by apenney** [comment] 2019-12-30 21:13
Just to chime in that I see this also and it's spamming my logs (on helm v3)

**Comment by kav** [comment] 2020-01-02 22:17
It also appears the helm operator might be looping on upgrading the same HR object since I'm seeing `pending-upgrade` and activity on the hr ever after it successfully installed. Happy to toss in some logs or investigate

**Comment by stefansedich** [comment] 2020-01-03 17:32
I am also seeing the same with rc5 and the datadog chart, my datadog installation was up to revision 5000 or so seems to be deploying over and over on each sync loop, thought I would try the latest dd agent chart to no avail and it only appears to be happening with this one chart.

**Comment by demisx** [comment] 2020-01-07 19:33
Same here. Seeing a bunch of these with `prometheus-operator` in `helm-operator-0.4.0/1.0.0-rc5` chart:

```
ts=2020-01-07T19:30:32.243215958Z caller=annotator.go:100 component=release
 release=prometheus-operator targetNamespace=monitoring
 resource=monitoring:helmrelease/prometheus-operator helmVersion=v2 
err="Object 'Kind' is missing in 'null'"
...
```
