### ISSUE TITLE
High memory usage in chart 1.4.4

### ISSUE THREAD

**Issue by ovitor** [fluxcd/helm-operator#666] opened 2022-09-14 18:55 UTC
**Describe the bug**

We were using a very old version of fluxcd/helm-operator chart, v0.7.0, recently we've upgraded our Kubernetes cluster and this chart alongside it (to version 1.4.4). After upgrading to v1.4.4 we've noticed a high memory utilization by its pods, causing endless evictions/terminations.

![memory-1 4 4](https://user-images.githubusercontent.com/997100/190240148-7926c9fc-ee48-4ce0-8606-2023294197c8.png)

After we've downgraded from v1.4.4 to v1.4.3 this issue doesn't take place any more.

![memory-1 4 3](https://user-images.githubusercontent.com/997100/190240444-8f00ca88-9d22-4fd2-b180-c73822ba2986.png)

```
helm-operator-7bbb785c87-2klmd             0/1     Completed                3 (15h ago)     17h
helm-operator-7bbb785c87-2vfgr             0/1     ContainerStatusUnknown   1               14h
helm-operator-7bbb785c87-54ksx             0/1     Completed                0               13h
helm-operator-7bbb785c87-5h9rv             0/1     Completed                0               42m
helm-operator-7bbb785c87-5sr2r             0/1     ContainerStatusUnknown   1               10h
helm-operator-7bbb785c87-5xtvs             0/1     ContainerStatusUnknown   2 (6h47m ago)   7h37m
helm-operator-7bbb785c87-9llhf             0/1     ContainerStatusUnknown   1               10h
helm-operator-7bbb785c87-9q7pj             0/1     ContainerStatusUnknown   1               14h
```

**To Reproduce**

1. Install v1.4.4
2. observe high memory usage

**Additional context**

- Helm Operator version: 1.4.4
- Kubernetes version: v1.24.3-gke.2100

**Comment by kingdonb** [comment] 2022-09-16 12:51
Greetings,

This could be caused by any number of things, we have upgraded all dependencies to mitigate as many CVEs as possible.

If you can narrow down the cause, it will be useful for the catalog, but at this point please understand Helm Operator is not recommended to be used by anyone, all feature development and testing is undertaken on Helm Controller. The memory use has been specially targeted in recent versions of Helm Controller to ensure that memory issues of the Helm CLI (which is not designed as a memory-resident package but as a CLI which can expect to be cleaned up after when the install is finished...) do not "leak" during normal operation of Helm Controller.

This kind of attention is not possible to replicate today on Helm Operator due to limited resources in our Open Source project team, our attention is focused on the new development.

**Comment by ovitor** [comment] 2022-09-28 13:46
No problem @kingdonb, I'm aware that you guys are heavily working on Flux v2 and the best approach is to upgrade to it. The idea was just to point out that this error could appear.

**Comment by kingdonb** [comment] 2022-09-28 18:54
We can leave the issue open for visibility, I went through and closed all issues that are over 1 year old with no activity, but this is about a recent release of Helm Operator, so it is still relevant 👍 

Thanks for reporting @ovitor

**Comment by kingdonb** [comment] 2022-11-01 12:59
We will be archiving the Helm Operator repo very soon, as described by:

* #667 

Please upgrade to Helm Controller and Flux v2, where loads of focus has been expended to ensure that memory usage is as efficient as possible, among every other concern. Closing now, as there will be no more work on Helm Operator in this repo.

For migration support, please consult the migration guide: https://fluxcd.io/flux/migration/flux-v1-migration/ or contact us in the [Flux channel on CNCF Slack](https://cloud-native.slack.com/channels/flux) where we still offer migration assistance, and workshops that are sponsored by the Flux project members and their supportive team at Weaveworks.

**Closed as not planned by kingdonb** 2022-11-01 12:59 UTC
Labels: bug
