### ISSUE TITLE
Authentication for private helm chart repository fails

### ISSUE THREAD

**Issue by anekdoti** [fluxcd/helm-operator#199] opened 2020-01-10 15:28 UTC
**Describe the bug**
Authentication to a private Helm repository defined in repositories.yaml with username and password fails and the corresponding HelmRelease is not released (other HelmReleases using public repositories are released/upgraded successfully).

The repositories.yaml is in the right place in the helm-operator container. Furthermore, adding the repo $REPO_URL with the same username and password using
```
helm3 repo add $REPO_NAME $REPO_URL --username $USERNAME --password $PASSWORD
```
suceeds in a shell running the helm-operator container.

**To Reproduce**
Steps to reproduce the behaviour:
I am running the helm-operator in a multi-tenancy FluxCD environment as described [https://github.com/fluxcd/multi-tenancy/blob/master/README.md](url). The helm-operator and its resources are provided in a folder in the cluster git repository. 
1. Add private repository with username and password to repositories.yaml (which is mounted as a secret into the helm-operator container).
2. Add HelmRelease referring to this repository to the git repository managing $NAMESPACE.
3. sync Flux

**Expected behavior**
The helm-operator should get the chart from the private repository and release the HelmRelease.

**Logs**
```
caller=release.go:142 component=release release=session-counter-job targetNamespace=$NAMESPACE resource=$NAMESPACE:helmrelease/$RELEASENAME helmVersion=v3 error="chart unavailable: looks like \"$REPO_URL\" is not a valid chart repository or cannot be reached: failed to fetch $REPO_URL/index.yaml : 401 Unauthorized"
```

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 1.0.0-rc5
- Targeted Helm version: v3
- Kubernetes version: 1.15.5
- Git provider: GitLab
- Container and Helm chart registry provider: Harbor

**Comment by hiddeco** [comment] 2020-01-10 15:35
Duplicate of #186, fixed in `rc7`.

**Closed as completed by hiddeco** 2020-01-10 15:35 UTC
Labels: bug, blocked needs validation, helm v3
