### ISSUE TITLE
Send helm-operator events to upstream

### ISSUE THREAD

**Issue by oliviabarrick** [fluxcd/helm-operator#13] opened 2018-09-05 01:39 UTC
We currently send Flux events to Weave Cloud as events allowing upstreams to be aware of syncs, releases, and other events in Flux.

It would be great to be able to produce events from the helm-operator whenever it makes changes (or fails to make changes).

Are there any plans for sending events from the helm-operator upstream?

**Comment by stefanprodan** [comment] 2019-08-13 10:29
Duplicate of #11

**Comment by kingdonb** [comment] 2022-09-02 19:12
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙

**Closed as completed by kingdonb** 2022-09-02 19:12 UTC
Labels: duplicate, blocked design
